### ISSUE TITLE
JSON parsing issues with embedding create with large batch size.

### ISSUE THREAD

**Issue by ellisonbg** [openai/openai-python#235] opened 2023-03-01 02:31 UTC
### Describe the bug

When I call `Embedding.create` with a large number of text chunks (batch) I get JSON decoding errors in the reponse. If I keep the batch size small (say 50) it works fine, but for large batch sizes (say 12k) it shows this problem. Looks very similar to the problems seen in #184. I initially saw this when using langchain, but reproduced the openai alone. Oddly, I sometimes get an `InvalidRequestError` instead.

### To Reproduce

Run the following code:

```python
texts = ["AI"*100 for i in range(4000)]
e = openai.Embedding.create(input=texts, model="text-embedding-ada-002")
```

### OS

macOS

### Python version

Python 3.11

### Library version

0.26.5

**Comment by kenn** [comment] 2023-03-11 01:52
Ditto, and bump.

v0.27.1

The problem is two-fold:

* sometimes `response` becomes plain `str`, not a real object
* tenacity makes it worse — retry on a clearly erroneous case on the client side. 
  * should only retry on 500 server errors, not on client errors. It's guaranteed to fail again and waste of resource on both ends + wait longer until timeout for the user.

```bash
Traceback (most recent call last):
  File "/proj/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 147, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, engine=engine).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/.venv/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 38, in create
    for data in response.data:
                ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'data'
```

Here's an example Response in `str` that's been failing:

```json
{
  "object": "list",
  "data": [
    {
      "object": "embedding",
      "index": 0,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 1,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 2,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 3,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 4,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 5,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 6,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 7,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 8,
      "embedding": "..."
    },
    {
      "object": "embedding",
      "index": 9,
      "embedding": "..."
    }
  ],
  "model": "text-embedding-ada-002-v2",
  "usage": {
    "prompt_tokens": 7481,
    "total_tokens": 7481
  }
}
```

**Comment by kenn** [comment] 2023-03-11 02:25
Probably related:

https://github.com/jerryjliu/gpt_index/issues/579

```py
openai.error.InvalidRequestError: [''] is not valid under any of the given schemas - 'input'
```

**Comment by kenn** [comment] 2023-03-11 02:35
OK this bug won't occur with `v0.27.0` so it seems like a `v0.27.1` specific issue.

**Comment by rattrayalex** [comment] 2023-12-31 00:01
This should be resolved in v1 of this library. If that's not the case, please open a new issue.

**Closed by rattrayalex** 2023-12-31 00:01 UTC
Labels: bug
