### ISSUE TITLE
JSON errors not decoded into APIError correctly

### ISSUE THREAD

**Issue by pencil** [openai/openai-python#734] opened 2023-11-08 16:27 UTC
The following code does not work as expected since the release of 1.0:

```python
import openai
client = openai.Client(api_key='...')
file = open('demo.wav', 'rb')
try:
    client.audio.transcriptions.create(model="whisper-1", file=file)
except openai.BadRequestError as e:
    print(e.code)
    print(e.message)
```

This prints
```
None
Error code: 400 - {'error': {'message': 'Audio file is too short. Minimum audio length is 0.1 seconds.', 'type': 'invalid_request_error', 'param': 'file', 'code': 'audio_too_short'}}
```
so it appears `e.code` is not getting set correctly to the expected value of `audio_too_short`. Similarly `param` and `type` are not getting decoded correctly from the error response.

Here is a 0s WAV file that can be used to reproduce the issue: [demo.wav.zip](https://github.com/openai/openai-python/files/13299045/demo.wav.zip)

**Comment by RobertCraigie** [comment] 2023-11-09 19:15
Thanks for the bug report, I can reproduce the error. Working on a fix.

**Comment by RobertCraigie** [comment] 2023-11-09 21:49
This has been fixed in v1.2.2!

**Closed by RobertCraigie** 2023-11-09 21:49 UTC
Labels: bug

**Comment by pencil** [comment] 2023-11-09 22:02
@RobertCraigie Thank you for the quick fix! I just tested 1.2.2 and can confirm that this is now fixed.

**Comment by take0x** [comment] 2023-11-10 15:09
In this context, `print(e.message)` shows the same message as `print(e)`.
Is this by design? Is there a way to get `message`?

**Comment by RobertCraigie** [comment] 2023-11-10 15:14
Ah that is a separate bug, thanks for reporting!

**Comment by take0x** [comment] 2024-01-22 14:48
> In this context, `print(e.message)` shows the same message as `print(e)`. Is this by design? Is there a way to get `message`?

It doesn't seem to have been fixed yet in v1.9.0.
Could someone please fix it?

**Comment by RobertCraigie** [comment] 2024-01-23 10:38
Ah sorry for the delay in fixing this @take0x, this is a little tricky.

Right now you can get the message that the API responded with by using `err.body.get('message')`.

**Comment by take0x** [comment] 2024-01-25 01:34
> Ah sorry for the delay in fixing this @take0x, this is a little tricky.
> 
> Right now you can get the message that the API responded with by using `err.body.get('message')`.

Thank you for the alternative suggestion. I'll try it!
