### ISSUE TITLE
Function Calling with AzureOpenAI

### ISSUE THREAD

**Issue by shashankdeshpande** [openai/openai-python#926] opened 2023-12-04 09:33 UTC
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I am attempting to utilize function calling with the chat completions API using `AzureOpenAI`, referring to the example given here - https://platform.openai.com/docs/guides/function-calling

While standard chat completions work as expected, I am encountering an error specific to function calling.

```bash
NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```
<img width="1117" alt="Screenshot 2023-12-04 at 2 42 53 PM" src="https://github.com/openai/openai-python/assets/47742503/8106206b-1d46-438b-bbda-cfafa1ecd5af">

Relevant code snippets are attached for reference.

**It's worth noting that the code works seamlessly when initializing the client with `OpenAI` but encounters issues with `AzureOpenAI` as outlined above**

### To Reproduce

1. Initialize client with `AzureOpenAI`
2. Define set of functions
3. Call the chat completion with the user query and a set of functions

### Code snippets

```Python
from openai import AzureOpenAI

client = AzureOpenAI(
    api_key="API_KEY",
    api_version="API_VERSION,
    azure_endpoint="API_ENDPOINT"
)

tools = [
    {
        "type": "function",
        "function": {
            "name": "get_current_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, e.g. San Francisco, CA",
                    },
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                },
                "required": ["location"],
            },
        },
    } 
]

response = client.chat.completions.create(
    model="DEPLOYMENT_NAME",
    messages=[{"role": "user", "content": "What's the weather like in San Francisco, Tokyo, and Paris?"}],
    tools=tools,
    tool_choice="auto"
)
```

### OS

macOS

### Python version

Python v3.9.16

### Library version

openai v1.3.7

**Comment by kristapratico** [comment] 2023-12-04 17:27
@shashankdeshpande can you share which model and API version you are using?

**Comment by kristapratico** [comment] 2023-12-04 20:30
@shashankdeshpande you need to update your API version to use `tools`. At a minimum, I tested that `2023-07-01-preview` works, but you might as well update to the latest version `2023-12-01-preview`

**Comment by kristapratico** [comment] 2023-12-06 17:28
I'm hearing that `tools` works with the latest preview version of gpt-4 (1106-preview): https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-preview-models

Can you give that a try?

**Comment by LudoArno** [comment] 2023-12-07 16:23
> > > I'm hearing that `tools` works with the latest preview version of gpt-4 (1106-preview): https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-preview-models
> > > Can you give that a try?
> > 
> > 
> > We do not have access to the preview model, but we would like to be able to use function calling with gpt-3.5 as well due to cost differences, etc.
> 
> I am unsure why, but it seems the issue has resolved itself for me, the SDK is working as expected now. Apologies for any inconvenience.

I would be interested to know why, in my case nothing has changed I currently found a way to make it work however it is a mix between old and current code example from the documentation

**Comment by LudoArno** [comment] 2023-12-08 10:52
> > > > > I'm hearing that `tools` works with the latest preview version of gpt-4 (1106-preview): https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-preview-models
> > > > > Can you give that a try?
> > > > 
> > > > 
> > > > We do not have access to the preview model, but we would like to be able to use function calling with gpt-3.5 as well due to cost differences, etc.
> > > 
> > > 
> > > I am unsure why, but it seems the issue has resolved itself for me, the SDK is working as expected now. Apologies for any inconvenience.
> > 
> > 
> > I would be interested to know why, in my case nothing has changed I currently found a way to make it work however it is a mix between old and current code example from the documentation
> 
> @LudoArno can you share your example code, including the model and API version you're using?

Here is the code, based on the documentation exemple but modified in order to work with azure.

My model is gpt-4-32k and api_version 2023-12-01-preview

In the documentation they explain that the endpoint accept both functions, function_call and tools, tool_choice parameters however when using tools, tool_choice with the correct format
Here is the error:
`BadRequestError: Error code: 400 - {'error': {'message': 'Unrecognized request arguments supplied: tool_choice, tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}`
```
client = AzureOpenAI(
    api_version="2023-12-01-preview",
    azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
    api_key=os.environ["AZURE_OPENAI_KEY"],
)

def get_current_weather(location, unit="fahrenheit"):
    """Get the current weather in a given location"""
    if "tokyo" in location.lower():
        return json.dumps({"location": "Tokyo", "temperature": "10", "unit": "celsius"})
    elif "san francisco" in location.lower():
        return json.dumps({"location": "San Francisco", "temperature": "72", "unit": "fahrenheit"})
    elif "paris" in location.lower():
        return json.dumps({"location": "Paris", "temperature": "22", "unit": "celsius"})
    else:
        return json.dumps({"location": location, "temperature": "unknown"})

functions = [
    {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "The city and state, e.g. San Francisco, CA",
                },
                "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
            },
            "required": ["location"],
        },
    },
]

def run_conversation(functions):

    messages = [{"role": "user", "content": "What's the weather like in San Francisco, Tokyo, and Paris?"}]

    response = client.chat.completions.create(
        model=os.environ["model"],
        messages=messages,
        functions=functions,
        function_call="auto",
    )
    response_message = response.choices[0].message
    functions_calls = response_message.function_call

    if functions_calls:

        available_functions = {
            "get_current_weather": get_current_weather,
        }
        messages.append(
        {
            "role": response_message.role,
            "function_call": {
                "name": response_message.function_call.name,
                "arguments": response_message.function_call.arguments,
            },
            "content": None
        })
        
        if isinstance(functions_calls, list):
            print("functions_calls is a list")
            pass
        else:
            functions_calls = [functions_calls]
            
        for function_call in functions_calls:
            function_name = function_call.name
            function_to_call = available_functions[function_name]
            function_args = json.loads(function_call.arguments)
            function_response = function_to_call(
                location=function_args.get("location"),
                unit=function_args.get("unit"),
            )
            messages.append(
                {
                    "role": "function",
                    "name": function_name,
                    "content": function_response,
                }
            )
            
        second_response = client.chat.completions.create(
            model=os.environ["model"],
            messages=messages)
        second_message = second_response.choices[0].message
        messages.append({
            "role": second_message.role,
            "content": second_message.content
            })
    else:
        messages.append(
            {
                "role": response_message.role,
                "content": response_message.content
            }
        )
    return messages
    
    
print(run_conversation(functions))
```

you can see that I am using part of the [previous code example](https://github.com/MicrosoftDocs/azure-docs/blob/bb65ede850a9099d48d0c91d84138e0494f6911c/articles/ai-services/openai/how-to/function-calling.md)
But still have to use the new structure with client and `response.choices[0].message.content` instead of the previous `second_response["choices"][0]["message"]` while having append dict instead of ChatCompletion object or others.

Note that even on [Azure documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling?tabs=python-new) there is unconsistent examples

**Comment by kristapratico** [comment] 2023-12-11 22:24
> BadRequestError: Error code: 400 - {'error': {'message': 'Unrecognized request arguments supplied: tool_choice, tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}

My understanding is that, for Azure, `tools` is supported by the latest preview gpt-4 model version only. So combination `gpt-4-1106-preview` and API version `2023-12-01-preview` is needed to make this work. Are you able to deploy the preview model? Here's some info on [regional availability](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-preview-model-availability).

> But still have to use the new structure with client and response.choices[0].message.content instead of the previous second_response["choices"][0]["message"]

Yes, v1.X of the openai library returns pydantic models, instead of plain dicts. You can convert the the response to a dictionary if you want with `second_response.model_dump()` so you can access it like `second_response["choices"][0]["message"]`.

> ...while having append dict instead of ChatCompletion object or others.

I recognize this pain point. The Azure service team is looking at making this possible in a manner that doesn't introduce breaking changes. For now, the workaround in your code is necessary. 

Good call out on the documentation. Having part of the example use the v1 library and the second half use v0 is a bit confusing. I'll open an issue to clean that up.

**Comment by brooksj0** [comment] 2024-01-31 21:52
Came across this myself, was resolved by switching from 3.5-turbo to 3.5-turbo-16k

```python
config_list = [{
    "api_key": os.environ.get("OPENAI_API_KEY"),
    "api_type": "azure",
    "base_url": os.environ.get("AZURE_OPENAI_ENDPOINT"),
    "api_version": os.environ.get("OPENAI_API_VERSION"),

    # 👎
    # "azure_deployment": "chat-35-deployment-name",
    # "model": "gpt-3.5-turbo",

    # 👍
    "azure_deployment": "chat-35-16k-deployment-name",
    "model": "gpt-3.5-turbo-16k",
}]
```

**Comment by simjaecheol** [comment] 2024-02-15 11:36
@brooksj0 it did'nt work for me :(

I'm having the same problem, is there any other solution?

I use `openai==1.11.1`.

**Comment by rattrayalex** [comment] 2024-02-15 15:06
@kristapratico can you share which models support tools in Azure OpenAI at this point?

Regardless, this is not a bug in the client library so I'm going to go ahead and close this issue.

**Closed** 2024-02-15 15:07 UTC
Labels: bug

**Comment by kristapratico** [comment] 2024-02-15 17:53
@simjaecheol can you share the error/stack trace or more details about what's not working?

For Azure API, function calling with tools is supported by the following:

Supported models
- gpt-35-turbo (1106)
- gpt-4 (1106-preview)

Supported API versions
- 2023-12-01-preview and newer

**Comment by simjaecheol** [comment] 2024-02-15 23:07
Thank you for telling me what is supported.

It works well because I changed it as you told me. :)

**Comment by AnjaliKeshri** [comment] 2024-05-07 12:09
hi @shashankdeshpande is your code working fine now?
