### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u201d' in position 59: ordinal not in range(128)

### ISSUE THREAD

**Issue by Nghiauet** [openai/openai-python#787] opened 2023-11-11 17:01 UTC
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I run the code from docs but receive the error 
**I find the cause of the bug is text load from .env have some special character.** 
```
from dotenv import load_dotenv
load_dotenv()
import os
openai.api_key = os.getenv("OPENAI_API_KEY")
```
**and solved with** 
```
client = OpenAI(
      api_key="sk...."
)
```
Seem have something weird when load .env file
My .env file is and I still use it for other code. But dont know this version receive error

I use new .venv of python 3.10.12 only install python-dotenv

### To Reproduce

!pip install python-dotenv
!pip install openai

RUN the code snip set

I still can print  
`print(u"\u201d")`

### Code snippets

```Python
import openai
from openai import OpenAI

from dotenv import load_dotenv
load_dotenv()
import os
openai.api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI()
response = client.chat.completions.create(
  model="gpt-3.5-turbo",
    response_format={ "type": "json_object" },

  messages=[
    {"role": "system", "content": "You are 3translator to translate the input text to destination language the input is the text nees to translate. First: Detect the language of the input text Second: Translate the input text from the detected language in first step to the Vietnamese language Third: Return output only the translated text not add up the description"},
    {"role": "user", "content": "this is a cat"},
  ]
)
```

### OS

ubuntu 22.04.3

### Python version

3.10.12

### Library version

openai 1.2.3

**Comment by BlueHephaestus** [comment] 2023-12-19 00:12
I'm not sure if you managed to fix your issue, but it seems to have been caused by the [Right Double Quote](https://www.compart.com/en/unicode/U+201D) being somewhere in your env file or in your code, which is quite a buggar to track down. I'm glad you figured it out! 

I did notice on trying to run your code that it didn't work however, due to first the model type being used, then the lack of the word "JSON" in the query string. Here's the fixed version of it after the fact if you're still having issues:
```python
import openai
from openai import OpenAI

from dotenv import load_dotenv
load_dotenv()
import os
openai.api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI()
response = client.chat.completions.create(
  model="gpt-3.5-turbo-1106",
    response_format={ "type": "json_object" },

  messages=[
    {"role": "system", "content": "You are 3translator to translate the input text to destination language the input is the text nees to translate. First: Detect the language of the input text Second: Translate the input text from the detected language in first step to the Vietnamese language Third: Return output only the translated text not add up the description, and return it in JSON format."},
    {"role": "user", "content": "this is a cat"},
  ]
)
print(response.choices[0].message.content)
```
Which produces:

```bash
$ python3 test.py 
{
  "translatedText": "đây là một con mèo"
}
```

If that's solved your problem, feel free to close this issue. Good luck with your project!

**Comment by rattrayalex** [comment] 2023-12-19 03:11
Glad you were able t find the problem!

**Closed by rattrayalex** 2023-12-19 03:11 UTC
Labels: bug
