### ISSUE TITLE
ImportError: cannot import name 'override' from 'typing_extensions' with openai==1.2.0

### ISSUE THREAD

**Issue by glejdis** [openai/openai-python#751] opened 2023-11-09 14:13 UTC
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

ImportError                               Traceback (most recent call last)
File <command-2965749824381288>, line 4
      2 from langchain.embeddings import OpenAIEmbeddings, AzureOpenAIEmbeddings
      3 #import openai
----> 4 from openai import AzureOpenAI 
      5 def utils_embedding(input_chunk, OPENAI_API_KEY, deployment_str = "xxxxx, api_base = "xxxx"):
      7     OPENAI_API_KEY = XXX)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-853491b7-ec2b-411d-9c68-bdb8f2c9309a/lib/python3.10/site-packages/openai/__init__.py:6
      3 from __future__ import annotations
      5 import os as _os
----> 6 from typing_extensions import override
      8 from . import types
      9 from ._types import NoneType, Transport, ProxiesTypes

ImportError: cannot import name 'override' from 'typing_extensions' (/databricks/python/lib/python3.10/site-packages/typing_extensions.py)

### To Reproduce

import openai

### OS

windows

### Python version

python v3.10.12

### Library version

openai v1.2.0

**Comment by samedovzaur** [comment] 2023-11-09 14:18
I'm getting AzureOpenAI importing error as well :(

**Comment by RobertCraigie** [comment] 2023-11-09 14:40
> I'm getting AzureOpenAI importing error as well :(

@samedovzaur Can you share an example snippet / error?

**Comment by samedovzaur** [comment] 2023-11-09 14:43
> > I'm getting AzureOpenAI importing error as well :(
> 
> @samedovzaur Can you share an example snippet / error?

Opened a new issue called AzureOpenAI error, but let me paste it in here:
This is the code I've taken from microsoft Azure documentation:

import os
from openai import AzureOpenAI

llm = AzureOpenAI(
  api_key = azureAPIKey_4,
  api_version = apiVersion,
  azure_endpoint = baseURL_4,
)

This is the error:
ImportError: cannot import name 'AzureOpenAI' from 'openai' (/usr/local/lib/python3.10/dist-packages/openai/__init__.py)

**Comment by glejdis** [comment] 2023-11-09 14:52
@RobertCraigie I have been using v4.5

**Comment by RobertCraigie** [comment] 2023-11-09 14:54
@glejdis What does this command output for you?

```sh
python -c 'from importlib.metadata import version; print(version("typing_extensions"))'
```

**Comment by glejdis** [comment] 2023-11-09 14:55
@RobertCraigie  4.5.0

**Comment by RobertCraigie** [comment] 2023-11-09 14:58
hmm are you running it in the same environment as your original report?

What if you replace the script you had before with this?

```py
from importlib.metadata import version

print(version("typing_extensions"))
```

**Comment by glejdis** [comment] 2023-11-09 14:59
@RobertCraigie it is still 4.5.0 and yes I am on the same environment. I am running the code as a notebook in Databricks

**Comment by RobertCraigie** [comment] 2023-11-09 15:01
Okay I'm not sure what could be causing your issue then because `4.5.0` definitely includes `override`:

- This is the [tag](https://github.com/python/typing_extensions/releases/tag/4.5.0) that corresponds to the `v4.5.0` release
- Here's the [link](https://github.com/python/typing_extensions/blob/8dcd89993c3926d6c704232b9c56160447fa81fe/src/typing_extensions.py#L2098) to the `override` definition in the code

Can you try upgrading to the latest `typing-extensions` version?

**Comment by glejdis** [comment] 2023-11-09 15:14
@RobertCraigie Thank you so much for your help but I already updated the typing-extensions package to the latest version but the error is still there.

**Comment by RobertCraigie** [comment] 2023-11-09 15:19
Can you reproduce this issue outside of databricks?

**Comment by glejdis** [comment] 2023-11-09 18:07
An update: I replaced "OpenAIEmbeddings" function with "AzureOpenAIEmbeddings". And the previous error did not appear anymore. However, now I receive this error: NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by rattrayalex** [comment] 2023-11-10 03:02
Could you share a Replit or similar reproduction?

**Comment by snehaa2632000** [comment] 2023-11-10 07:40
> An update: I replaced "OpenAIEmbeddings" function with "AzureOpenAIEmbeddings". And the previous error did not appear anymore. However, now I receive this error: NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

where should this change be made?

**Comment by glejdis** [comment] 2023-11-10 07:45
@RobertCraigie @snehaa2632000 Here is the code 
def utils_embedding(input_chunk, OPENAI_API_KEY, deployment_str = "text-embedding-ada-002", api_base = "https://xxx"):
    
    OPENAI_API_KEY = dbutils.secrets.get(scope = "tokens", key = "xxx")
    openai.api_type = "azure"
    openai.api_base = "https://xxx"
    openai.api_version = "2023-08-01-preview"
    openai.api_key = OPENAI_API_KEY
    os.environ["OPENAI_API_TYPE"] = openai.api_type
    os.environ["OPENAI_API_BASE"] = openai.api_base
    os.environ["OPENAI_API_VERSION"] = openai.api_version
    os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

    with get_openai_callback() as cb:
        # embeddings
        embeddings = AzureOpenAIEmbeddings(deployment = deployment_str,
                                model="text-embedding-ada-002",
                                api_key = openai.api_key,
                                api_version=openai.api_version
                                )
        embedding = embeddings.embed_query(input_chunk)
    total_tokens = cb.total_tokens
    prompt_tokens = cb.prompt_tokens
    completion_tokens = cb.completion_tokens
    cost_per_chunk = utils_calculate_costs(deployment_name = deployment_str, prompt_tokens = prompt_tokens, completion_tokens = completion_tokens)

    return embedding, cost_per_chunk

OPENAI_API_KEY = dbutils.secrets.get(scope = "tokens", key = "xxx")
parsed_chunk = "Hi how are you?"
embedding, embedding_costs = utils_embedding(parsed_chunk, OPENAI_API_KEY = OPENAI_API_KEY, api_base = "https://xxx", deployment_str = "text-embedding-ada-002")

**Comment by snehaa2632000** [comment] 2023-11-10 08:39
I am also getting the same issue on Databricks:
**Error -**
```
----> 1 from openai import OpenAI

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you're seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-3765dafa-be7e-4bea-991a-3ff3971c3373/lib/python3.9/site-packages/openai/__init__.py:6
      3 from __future__ import annotations
      5 import os as _os
----> 6 from typing_extensions import override
      8 from . import types
      9 from ._types import NoneType, Transport, ProxiesTypes
```

> ImportError: cannot import name 'override' from 'typing_extensions' (/databricks/python/lib/python3.9/site-packages/typing_extensions.py)


Current specs :

- successfully upgraded typing-extensions to 4.8.0
- successfully installed openai==1.2.2

**Comment by RobertCraigie** [comment] 2023-11-10 08:47
@snehaa2632000 can you try importing it yourself and if that fails, report an issue to databricks as this appears to be unrelated to the openai package. It also looks like they're doing import patching.
```py
from typing_extensions import override
```

**Comment by snehaa2632000** [comment] 2023-11-10 08:50
> @snehaa2632000 can you try importing it yourself and if that fails, report an issue to databricks as this appears to be unrelated to the openai package. It also looks like they're doing import patching.
> 
> ```python
> from typing_extensions import override
> ```

It still fails if I try importing myself. I will raise an issue to Databricks.

**Comment by glejdis** [comment] 2023-11-10 11:44
> Could you share a Replit or similar reproduction?

The error still persists. This is the error: NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by RobertCraigie** [comment] 2023-11-10 11:46
@glejdis can you share a full code snippet? The snippet you shared doesn't include imports.

**Comment by glejdis** [comment] 2023-11-10 11:46
> @RobertCraigie @snehaa2632000 Here is the code
> 
> def utils_embedding(input_chunk, OPENAI_API_KEY, deployment_str = "text-embedding-ada-002", api_base = "https://xxx"):
> 
> ```
> OPENAI_API_KEY = dbutils.secrets.get(scope = "tokens", key = "xxx")
> openai.api_type = "azure"
> openai.api_base = "https://xxx"
> openai.api_version = "2023-08-01-preview"
> openai.api_key = OPENAI_API_KEY
> os.environ["OPENAI_API_TYPE"] = openai.api_type
> os.environ["OPENAI_API_BASE"] = openai.api_base
> os.environ["OPENAI_API_VERSION"] = openai.api_version
> os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
> 
> with get_openai_callback() as cb:
>     # embeddings
>     embeddings = AzureOpenAIEmbeddings(deployment = deployment_str,
>                             model="text-embedding-ada-002",
>                             api_key = openai.api_key,
>                             api_version=openai.api_version
>                             )
>     embedding = embeddings.embed_query(input_chunk)
> total_tokens = cb.total_tokens
> prompt_tokens = cb.prompt_tokens
> completion_tokens = cb.completion_tokens
> cost_per_chunk = utils_calculate_costs(deployment_name = deployment_str, prompt_tokens = prompt_tokens, completion_tokens = completion_tokens)
> 
> return embedding, cost_per_chunk
> ```
> 
> OPENAI_API_KEY = dbutils.secrets.get(scope = "tokens", key = "xxx") parsed_chunk = "Hi how are you?" embedding, embedding_costs = utils_embedding(parsed_chunk, OPENAI_API_KEY = OPENAI_API_KEY, api_base = "https://xxx", deployment_str = "text-embedding-ada-002")

@RobertCraigie I shared it here :)

**Comment by RobertCraigie** [comment] 2023-11-10 11:48
Sorry it wasn't clear, that code doesn't include imports, I'm not sure where `AzureOpenAIEmbeddings` is coming from.

**Comment by glejdis** [comment] 2023-11-10 11:48
from langchain.embeddings import AzureOpenAIEmbeddings

**Comment by RobertCraigie** [comment] 2023-11-10 11:52
Okay I think this is a langchain issue then, if you aren't on the latest version I'd recommend upgrading to the latest and testing again. If it still doesn't work then please open an issue on the langchain repository.

**Comment by RobertCraigie** [comment] 2023-11-10 12:34
I'm going to close this issue as the reported ImportError is a databricks bug and the current issue isn't related to this SDK.

**Closed by RobertCraigie** 2023-11-10 12:34 UTC

**Comment by ondrejhavlicek** [comment] 2023-11-15 10:11
This occurs in databricks runtime 13.x (and also 14.x with slightly different error), when installing openai using `!pip install openai`. If I switch to `%pip install openai`, everything works fine.. In runtime 12.2 it apparently does not matter if one uses !pip or %pip.

**Comment by rattrayalex** [comment] 2023-11-16 03:26
Should this be reported to databricks? Is there an issue tracker you could link to here with an issue?

**Comment by alejandrowassermannbfa** [comment] 2023-11-24 02:04
If you specify an older version of openai it works.  This version was suggested by chatgpt itself and it did the trick
%pip install openai==0.27.0

**Comment by loicmarie** [comment] 2023-11-30 09:52
Entered this issue in Databricks notebook as well, was able to fix it by running:
`dbutils.library.restartPython()`
Just after the `%pip install`

**Comment by ondrejhavlicek** [comment] 2023-11-30 11:54
I confirm that in runtime 13.3 ML it works like this
```
%pip install openai --upgrade

dbutils.library.restartPython()
```

The "upgrade" is needed because otherwise it keeps preinstalled version 0.27.8

**Comment by davies-w** [comment] 2023-12-21 19:50
I'm now having this issue in a fairly vanilla Google Colab Notebook (it was working last week, now it isn't!)

**Comment by rattrayalex** [comment] 2023-12-21 22:37
@davies-w if `from typing_extensions import override` does not work in the Colab notebook, please report that issue to Google Colab. If it does, and you still get the error mentioned in the title of this issue, please open a new issue with full details of your environment, your code, and the error you're seeing.

**Comment by 907Resident** [comment] 2024-01-19 01:12
> This occurs in databricks runtime 13.x (and also 14.x with slightly different error), when installing openai using `!pip install openai`. If I switch to `%pip install openai`, everything works fine.. In runtime 12.2 it apparently does not matter if one uses !pip or %pip.

Using the `%pip install openai` worked for me in databricks (14.0) after trying other installation methods. I am not certain why that is the case. I previously tried rolling back the `openai` version and that did not work; only when I used the magic command for some reason I was able to bypass the `ImportError`.

**Comment by lbcommer** [comment] 2024-01-25 11:58
Just 
`dbutils.library.restartPython()`
after installing the libraries worked for me.

**Comment by neurosageai** [comment] 2024-01-29 17:17
> @glejdis What does this command output for you?
> 
> ```shell
> python -c 'from importlib.metadata import version; print(version("typing_extensions"))'
> ```

4.3.0

**Comment by joshdunnlime** [comment] 2024-03-18 15:51
> Just `dbutils.library.restartPython()` after installing the libraries worked for me.

Yep. Worked for me too. Thanks!!!

**Comment by nadavc2c** [comment] 2024-04-06 20:10
Hi, For me what helped is using
`sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lib"))`
(change the path as required to be where you have the package).
This way, when you import it uses the correct package, and not Databricks / Splunk path `/databricks/python/lib/python3.10/site-packages/typing_extensions.py` which may be incompatible.

**Comment by usmanyaqoob49** [comment] 2024-07-12 11:31
pip install --upgrade typing_extensions

By upgrading typing_extensions using above command resolved my problem :)
