### ISSUE TITLE
Issue with updating the openai.proxy field

### ISSUE THREAD

**Issue by Comrade19632** [openai/openai-python#343] opened 2023-03-26 16:54 UTC
### Describe the bug

I'm experiencing an issue with updating the openai.proxy . When I make a request to OpenAI using this library, I set the openai.proxy field to a proxy value. However, if the request fails and I change the openai.proxy field to a different value, subsequent requests continue to use the old proxy value instead of the updated one.

### To Reproduce

1. Create an array of two elements, where the first element is an invalid proxy and the second element is a valid one.
2. Run a loop over this array, updating the value of openai.proxy each time, and attempt to make requests to the OpenAI API.
3. Requests will fail on all proxies, as the value of openai.proxy does not seem to change. Additionally, if a valid proxy is placed first, all requests will succeed, as if all proxies were valid.

### OS

ubuntu

### Python version

python:3.8.3

### Library version

openai==0.27.2

**Comment by hallacy** [comment] 2023-04-01 20:26
Hi @Comrade19632, that sounds like its probably working as intended. I don't think that the `requests` library allows dynamic changing of proxy, but I could be wrong.

Our sessions are thread-specific so I suspect the easiest way to get around this would be to close the thread and start a new one. I don't believe we currently have a way to end a session in a thread, though I imagine you could hack something together by deleting the `session` field from `_thread_context` in api_requestor.py.

I don't think we plan to change this behavior anytime soon, so I'm going to close this as not planned. Feel free to reopen if this isn't what you expected

**Closed by hallacy** 2023-04-01 20:26 UTC
Labels: bug
