### ISSUE TITLE
Module level Client forcefully loaded when in PyCharm debugger

### ISSUE THREAD

**Issue by taraskuzyk** [openai/openai-python#1352] opened 2024-04-21 19:13 UTC
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

If I run the following script simply via Python

```python
from openai import OpenAI

openai = OpenAI(api_key="MY KEY")

print("We got to the end!")
```

It works fine. However, in PyCharm's debugger, it seems like the ```_module_client``` is being forcefully initialized, so I get this error raised when trying to run on the ```from openai import OpenAI``` line

```python
# in _client.py
        if api_key is None:
            raise OpenAIError(
                "The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"
            )
```

The workaround that worked for me is conditionally loading the module client like this in ```__init__.py``` at the end of the file:

```python
import sys

gettrace = getattr(sys, 'gettrace', None)

if gettrace is None:
    # We're not in debug mode, load libraries
    from ._module_client import (
        beta as beta,
        chat as chat,
        audio as audio,
        files as files,
        images as images,
        models as models,
        batches as batches,
        embeddings as embeddings,
        completions as completions,
        fine_tuning as fine_tuning,
        moderations as moderations,
    )
```

### To Reproduce

Follow instructions from the description.

### OS

Windows 11

### Python version

3.12

### Library version

1.23.2

**Comment by rattrayalex** [comment] 2024-04-22 21:22
This is a duplicate of https://github.com/openai/openai-python/issues/1108 - but the tl;dr is that we view this as a bug in PyCharm and would very much appreciate it if you'd file a ticket with them.

**Closed by rattrayalex** 2024-04-22 21:22 UTC
Labels: bug
