### ISSUE TITLE
error_message='Resource not found' for gpt-35-turbo model in Azure OpenAI Service

### ISSUE THREAD

**Issue by eugene2candy** [openai/openai-python#362] opened 2023-04-02 01:41 UTC
### Describe the bug

It was successfully called via python openai library. But from a few days ago. It returns error_code=404 error_message='Resource not found' error_param=None error_type=None message='OpenAI API error received' stream_error=False. 

I am pretty sure that the model deployment is existed since I can still call the endpoint on Postman and get the response. 
And I also tried to delete and deploy it again in Azure OpenAI service. But still not work on python side. 

Is this issue from Microsoft side? or anyone can help me figure out?

### To Reproduce

```
response = openai.ChatCompletion.create(
        engine="NAME of Model Deployment",
        messages=msg,
        temperature=temperature,
        max_tokens=max_tokens,
        top_p=top_p,
        frequency_penalty=frequency_penalty,
        presence_penalty=presence_penalty,
        stop=stop)
```

### OS

macOS

### Python version

Python v3.10

### Library version

openai-python 0.27.2

**Comment by eugene2candy** [comment] 2023-04-02 12:45
The issue is resolved. Seems issue from Azure side. Now the code works.

**Comment by tao12345666333** [comment] 2023-04-05 21:56
Why didn't you pass the api version parameter?

**Comment by kristapratico** [comment] 2023-04-05 22:26
@eugene2candy can you share which API version you are using? ChatCompletion with the Azure service is supported with 2023-03-15-preview.

**Comment by eugene2candy** [comment] 2023-04-19 11:53
@tao12345666333 @kristapratico Sorry for late response, of course I passed api version. And it's 2023-03-15-preview for sure. I did it exactly as the sample code from Azure playground, it just not works. 
![image](https://user-images.githubusercontent.com/7625061/233066426-8eddbe6a-c264-4674-a9e9-ad2db604e531.png)

**Comment by kristapratico** [comment] 2023-04-19 23:59
@eugene2candy thanks. I'm having trouble reproducing this myself, so I hope you don't mind me asking a few more questions.

1) Can you confirm that if you try the request with cURL or Postman that it's successful?
1) Is there any chance you're using `http` instead of `https` for the endpoint? In this case, I do see the 404 error.
2) Would you be able to run the code with `openai.log = "debug"` and share the output?

**Comment by eugene2candy** [comment] 2023-04-20 00:35
> @eugene2candy thanks. I'm having trouble reproducing this myself, so I hope you don't mind me asking a few more questions.
> 
> 1. Can you confirm that if you try the request with cURL or Postman that it's successful?
> 2. Is there any chance you're using `http` instead of `https` for the endpoint? In this case, I do see the 404 error.
> 3. Would you be able to run the code with `openai.log = "debug"` and share the output?

@kristapratico 
Per your questions,
1. Yes, it's successful by using postman, cURL, or even C# OpenAI preview SDK. 
2. Not this problem. 
3. By adding `openai.log = "debug"`, I found the root cause for the problem: 
Actually I passed api_version by `openai.api_version = "2023-03-15-preview"` and obviously it doesn't work properly because the debug output shows that `api_version=2022-12-01`, which totally doesn't make sense. I tried to pass the api_version inside `openai.ChatCompletion.create` method and now it works... 
So, here is another question, does `openai.api_version = "2023-03-15-preview"` just not work? If so, I doubt that the sample code is incorrect from Azure portal. Or this might be a bug with python SDK.

**Comment by eugene2candy** [comment] 2023-04-20 00:40
```
openai.api_type = "azure"
openai.api_base = ""
openai.api_version = "2023-03-15-preview" # doesn't work when I passed the api version like this
openai.api_key = os.getenv("OPENAI_API_KEY")

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    try:
        msg = req.get_json().get("messages")
    except ValueError:
        pass

    openai.log = "debug"

    response = openai.ChatCompletion.create(
        engine="gpt4",
        #api_version="2023-03-15-preview",
        messages = msg)
```

**Comment by kristapratico** [comment] 2023-04-20 00:54
@eugene2candy Ah I see. Are you using version 0.27.2 like it says in your original comment? I don't think the `api_version` was updated to `2023-03-15-preview` until this [PR](https://github.com/openai/openai-python/pull/335/files). Can you upgrade to the latest version?

`pip install openai --upgrade`

I realize that doesn't explain why the code is not updating the `api_version` for you in the example you shared, but it might unblock you for now.

**Comment by eugene2candy** [comment] 2023-04-20 01:08
@kristapratico Actually I am using 0.27.4 currently. I can still reproduce the same problem. 
```
[2023-04-20T01:03:04.599Z] Worker process started and initialized.
[2023-04-20T01:03:07.141Z] Host lock lease acquired by instance ID '000000000000000000000000016D6639'.
[2023-04-20T01:04:20.287Z] Executing 'Functions.Chat' (Reason='This function was programmatically called via the host APIs.', Id=7a9bf531-2424-4e78-92e5-979ca504d273)
[2023-04-20T01:04:20.408Z] message='Request to OpenAI API' method=post path=https://<placeholder>.openai.azure.com//openai/deployments/gpt4/chat/completions?api-version=2022-12-01
[2023-04-20T01:04:20.408Z] api_version=2022-12-01 data='{"messages": [{"role": "system", "content": "You are an AI assistant that helps people find information."}, {"role": "user", "content": "\\u4f60\\u597d"}]}' message='Post details'
[2023-04-20T01:04:20.417Z] Python HTTP trigger function processed a request.
[2023-04-20T01:04:21.951Z] message='OpenAI API response' path=https://<placeholder>.openai.azure.com//openai/deployments/gpt4/chat/completions?api-version=2022-12-01 processing_ms=None request_id=None response_code=404
[2023-04-20T01:04:21.961Z] body='{"error":{"code":"404","message": "Resource not found"}}' headers="{'Content-Length': '56', 'Content-Type': 'application/json', 'apim-request-id': 'f2b3f9bc-f173-4ea7-91ce-93c779937328', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'Date': 'Thu, 20 Apr 2023 01:04:21 GMT'}" message='API response body'
[2023-04-20T01:04:21.965Z] error_code=404 error_message='Resource not found' error_param=None error_type=None message='OpenAI API error received' stream_error=False
[2023-04-20T01:04:21.973Z] error_code=404 error_message='Resource not found' error_param=None error_type=None message='OpenAI API error received' stream_error=False
[2023-04-20T01:04:22.082Z] Executed 'Functions.Chat' (Failed, Id=7a9bf531-2424-4e78-92e5-979ca504d273, Duration=1852ms)
[2023-04-20T01:04:22.083Z] System.Private.CoreLib: Exception while executing function: Functions.Chat. System.Private.CoreLib: Result: Failure
[2023-04-20T01:04:22.083Z] Exception: InvalidRequestError: Resource not found
[2023-04-20T01:04:22.083Z] Stack:   File "/usr/local/Cellar/azure-functions-core-tools@4/4.0.5095/workers/python/3.10/OSX/X64/azure_functions_worker/dispatcher.py", line 452, in _handle__invocation_request
[2023-04-20T01:04:22.083Z]     call_result = await self._loop.run_in_executor(
[2023-04-20T01:04:22.083Z]   File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
[2023-04-20T01:04:22.083Z]     result = self.fn(*self.args, **self.kwargs)
[2023-04-20T01:04:22.083Z]   File "/usr/local/Cellar/azure-functions-core-tools@4/4.0.5095/workers/python/3.10/OSX/X64/azure_functions_worker/dispatcher.py", line 718, in _run_sync_func
[2023-04-20T01:04:22.083Z]     return ExtensionManager.get_sync_invocation_wrapper(context,
[2023-04-20T01:04:22.083Z]   File "/usr/local/Cellar/azure-functions-core-tools@4/4.0.5095/workers/python/3.10/OSX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper
[2023-04-20T01:04:22.083Z]     result = function(**args)
[2023-04-20T01:04:22.083Z]   File "/Users/<placeholder>/Documents/GitHub/fn-gpt/Chat/__init__.py", line 21, in main
[2023-04-20T01:04:22.083Z]     response = openai.ChatCompletion.create(
[2023-04-20T01:04:22.083Z]   File "/Users/<placeholder>/Documents/GitHub/fn-gpt/.venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
[2023-04-20T01:04:22.083Z]     return super().create(*args, **kwargs)
[2023-04-20T01:04:22.083Z]   File "/Users/<placeholder>/Documents/GitHub/fn-gpt/.venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
[2023-04-20T01:04:22.083Z]     response, _, api_key = requestor.request(
[2023-04-20T01:04:22.083Z]   File "/Users/<placeholder>/Documents/GitHub/fn-gpt/.venv/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
[2023-04-20T01:04:22.083Z]     resp, got_stream = self._interpret_response(result, stream)
[2023-04-20T01:04:22.083Z]   File "/Users/<placeholder>/Documents/GitHub/fn-gpt/.venv/lib/python3.10/site-packages/openai/api_requestor.py", line 620, in _interpret_response
[2023-04-20T01:04:22.083Z]     self._interpret_response_line(
[2023-04-20T01:04:22.083Z]   File "/Users/<placeholder>/Documents/GitHub/fn-gpt/.venv/lib/python3.10/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
[2023-04-20T01:04:22.083Z]     raise self.handle_error_response(
[2023-04-20T01:04:22.083Z] .
```
![image](https://user-images.githubusercontent.com/7625061/233231217-61c829df-71c3-4b93-8215-7fc166da69b9.png)

**Comment by eugene2candy** [comment] 2023-04-20 01:18
Thanks for your help @kristapratico . My issue is gone anyway. Just wanna call out the potential issue with latest (0.27.4) version of the sdk and the misleading guide with the sample code from Azure portal...

**Comment by kristapratico** [comment] 2023-04-20 01:34
@eugene2candy Glad to hear things are working. I will continue to investigate what's going on with the `api_version` not getting set in the latest version. It looks like you're running this in an Azure function, so I'll try to reproduce this from there. Thanks for the additional context.

**Comment by shawnmittal** [comment] 2023-04-26 19:10
@kristapratico I'm hitting this same issue regarding the "resource not found" error using version 0.27.4 within my local wsl dev environment. I downgraded to version 0.27.0 and everything functions as expected. The openai package version is the only thing I changed.

I tried to re-create the issue by upgrading back to 0.27.4, but was unable to do so. I completely wiped my wsl install and reinstalled 0.27.4 and ran into the same problem.

Very odd bug to troubleshoot, but figured I'd provide some additional data points. I'm on Python 3.8.3.

**Comment by shawnmittal** [comment] 2023-04-26 19:14
As a note, bypassing the OpenAI package and just using REST calls works just fine every time, so it seems like something with the package itself may be at fault.

**Comment by kristapratico** [comment] 2023-04-26 19:40
Thanks for the additional data point, @shawnmittal. Is this also with ChatCompletions and gpt-35-turbo? Which API version are you specifying? I will try to reproduce this in WSL.

**Comment by shawnmittal** [comment] 2023-04-26 19:46
Yes, using ChatCompletions and gpt-35-turbo. API version "2023-03-15-preview".

**Comment by rattrayalex** [comment] 2024-03-03 00:45
This does not look like a bug in the SDK, so I'm going to go ahead and close this issue.

**Closed by rattrayalex** 2024-03-03 00:45 UTC
Labels: bug, Azure
