### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'ChatCompletion/Completion'

### ISSUE THREAD

**Issue by jqma-usc** [openai/openai-python#423] opened 2023-04-30 17:38 UTC
### Describe the bug

The feature is not working at all for me, so I created a new venv and it still does not work

### To Reproduce

```
import openai

openai.api_key = "key"

completion = openai.Completion.create(
         model="gpt-3.5-turbo", 
         messages=[{"role": "user", "content": "Hello world!"}]
)
```

### Code snippets

```Python
Additionally, I tried to run this cURL command in my terminal given by the openai documentation:

curl https://api.openai.com/v1/completions \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"prompt": YOUR_PROMPT, "model": FINE_TUNED_MODEL}'

and replaced it with my api key which in return printed:
    "error": {
        "message": "Incorrect API key provided: -*****************************************. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }

I've used 3 api keys at this point, I am not sure if that's what is causing the issue since both my python and openai are up to date.
```

### OS

macOS

### Python version

Python v3.11.3

### Library version

openai-python v0.27.5

**Comment by eyan02** [comment] 2023-05-03 19:21
@jqma-usc , **upgrading to openai-python v0.27.6 should solve the issue**. 
Looks like the ChatCompletion class was missing from the cli.py file.

**Alternatively, there are two other work-arounds:**
1. [Easy] Specify the api_base parameter to bypass the standard api_base url, this allows you to run a chat completion as expected (even though you are using Completion class):
`completion = openai.Completion.create(
         api_base="https://api.openai.com/v1/chat",
         model="gpt-3.5-turbo", 
         messages=[{"role": "user", "content": "Hello world!"}]
)`
2. [Medium] You can add the missing class into the cli.py file yourself. Just copy and past the Completion class (but be sure to change the class name to ChatCompletion).

**Comment by HMYDK** [comment] 2023-05-09 08:48
It's possible that the issue is caused by a local Python package named 'openai'.

**Comment by SonicandTailsCD** [comment] 2023-05-20 00:47
Hello! There's now a fix. Run in your terminal:
```cmd
pip uninstall openai
```
and then do
```cmd
pip install openai
```
and this should fix it! :)

**Comment by rkimbers** [comment] 2023-06-04 01:07
> Hello! There's now a fix. Run in your terminal:
> 
> ```batchfile
> pip uninstall openai
> ```
> 
> and then do
> 
> ```batchfile
> pip install openai
> ```
> 
> and this should fix it! :)

dont work :(

**Comment by Anotherlynn** [comment] 2023-07-18 03:21
It should be casued by a local file named 'openai'. I had the same issue and fixed by rename the local file.

**Closed** 2023-11-10 03:57 UTC
Labels: bug
