### ISSUE TITLE
Invalid URL (POST /v1/completions)

### ISSUE THREAD

**Issue by jillofall** [openai/openai-python#360] opened 2023-03-30 15:35 UTC
### Describe the bug

CHATGPT 4 will not allow new requests even though user haven't hit their request limitation and have paid for the plus subscription. They are also noticing their payment information has been removed from their account. They have found paying for an additional subscription has fixed the issue, even though they already have an active subscription.

### To Reproduce

open chatgpt4 and enter any request
The error pops up

### Code snippets

```Python
Invalid URL (POST /v1/completions)
```

### OS

macOS

### Python version

PYTHON V.7.1

### Library version

OPENAI-PYTHON V0.26.4

**Comment by hallacy** [comment] 2023-03-30 18:31
Thanks for writing in! 

I'm not entirely sure how to reproduce this issue. GPT4 and Turbo both only use the v1/chat/completions endpoint, so /v1/completions won't work there.  Can you provide more steps to reproduce?

**Comment by jillofall** [comment] 2023-03-30 18:40
Hi there! Here’s a screen recording of the issue. 

https://user-images.githubusercontent.com/120443689/228933254-ddd7fb38-2c29-4b1c-b348-313463300b1b.MOV

**Comment by morgenthum** [comment] 2023-03-30 19:48
Same issue here. A lot of people reported the same issue on discord

**Comment by Cerebrovinny** [comment] 2023-03-30 19:57
same here on Chat GPT 4 seems to be down for me

**Comment by hallacy** [comment] 2023-03-30 20:23
Unfortunately, this repo is only for openai-python bugs so I'm going to close this as something we can't work on. I believe the chatgpt team is working on this outside of this repo.

**Closed** 2023-03-30 20:23 UTC
Labels: bug

**Comment by expansive** [comment] 2023-03-30 21:11
Same issue here

**Comment by BNMwangi** [comment] 2023-03-30 22:10
> 
Same issue here . . . anybody found a solution to this?

**Comment by Pamm-j** [comment] 2023-03-30 23:33
Same issue here
