### ISSUE TITLE
`openai.AsyncOpenAI` not safe when shared across `async` tests

### ISSUE THREAD

**Issue by jamesbraza** [openai/openai-python#1777] opened 2024-10-06 01:57 UTC
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When sharing `AsyncOpenAI` across `async` tests, it's possible to hit `openai.APIConnectionError: Connection error.`

### To Reproduce

https://colab.research.google.com/drive/1icWDkN2iYPl3mxCEwA0-kE7GSSOeM9E8?usp=sharing

### Code snippets

```Python
import pytest
from openai import AsyncOpenAI

client = AsyncOpenAI()


@pytest.mark.asyncio
async def test_completion1() -> None:
    await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{
            "content": (
                "Here is a question, the correct answer to the question, and a proposed"
                " answer to the question. Please tell me if the proposed answer is"
                " correct, given the correct answer. ONLY SAY 'YES' OR 'NO'. No other"
                " output is permitted.\n\nQuestion: What is 25 * 10? \n\nCorrect"
                " answer: 250 \n\nProposed answer: 250"
            ),
            "role": "user",
        }],
    )


@pytest.mark.asyncio
async def test_completion2() -> None:
    await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{
            "content": (
                "Here is a question, the correct answer to the question, and a proposed"
                " answer to the question. Please tell me if the proposed answer is"
                " correct, given the correct answer. ONLY SAY 'YES' OR 'NO'. No other"
                " output is permitted.\n\nQuestion: What is 25 * 10? \n\nCorrect"
                " answer: 250 \n\nProposed answer: 250"
            ),
            "role": "user",
        }],
    )
```

### OS

linux

### Python version

3.10.12

### Library version

1.51.0

**Comment by RobertCraigie** [comment] 2024-10-06 02:00
Thanks for the report, what version of `httpx` / `httpcore` are you using? (I can't open the colab link right now)

**Comment by jamesbraza** [comment] 2024-10-06 02:06
Hello @RobertCraigie thanks for the quick response, it's `httpx=0.27.2` and `httpcore==1.0.6`

**Comment by rotem925** [comment] 2024-10-08 11:52
I see the same issue.
httpx==0.27.2
httpcore==1.0.6
In my case I use pytest with async and ainvoke on ChatOpenAI
BUT, if I use ChatBedrock, everything is working.

Since I was breaking my head against this, one hint is that I've tried to trace it
and I printed the "real" error which is not a connection error, but "Event loop is closed"

This is the line it fails, if you print the err object, you would see it.
https://github.com/openai/openai-python/blob/main/src/openai/_base_client.py#L1584
`raise APIConnectionError(request=request,message=str(err)) from err`

Hope that will give us some more insights..

**Comment by anointingmayami** [comment] 2024-10-08 12:02
update your OpenAI to the latest.

**Comment by anointingmayami** [comment] 2024-10-08 13:39
Thanks for reaching out. An update has been sent to fix the issue. We will
let you know once the issue is resolved.

God bless you. Grace be unto you and Peace be multiplied.

Anointing J. Mayami
+2348140070908
***@***.***

**Comment by bhumkong** [comment] 2024-10-09 09:54
It happens because by default pytest-asyncio creates a new event loop for each test. But your tests are using the same client. And when you try to use the same client concurrently from different event loops, this error occurs.

Change your test decorators to `pytest.mark.asyncio(loop_scope="session")`

**Comment by RobertCraigie** [comment] 2024-10-09 12:18
Thanks @bhumkong, I'm going to close this as it doesn't appear to be an SDK bug. Please re-open if you're still running into issues!

**Closed by RobertCraigie** 2024-10-09 12:18 UTC

**Comment by jamesbraza** [comment] 2024-10-09 16:52
Thank you @bhumkong, nice work and appreciate your breakdown

**Comment by rotem925** [comment] 2024-10-10 04:59
@bhumkong Thank you! I can confirm this worked.
