### ISSUE TITLE
JSONDecodeError when streaming chunks for ChatCompletion

### ISSUE THREAD

**Issue by jwayne** [openai/openai-python#650] opened 2023-10-12 02:35 UTC
### Describe the bug

`openai.ChatCompletion.acreate(..., stream=True)` seems to fail with a JSONDecodeError when it's called such that:
- the prompt alone doesn't exceed the rate limit
- the generated output + prompt together exceeds the rate limit

Example:
- Suppose my rate limit is 10000 tokens/min, and my prompt is 8000 tokens.
- If the generated output is 2000+ tokens, then I hit my rate limit before my response is finished streaming
- The first 2000 tokens stream successfully, but after I hit my rate limit, the OpenAI server streams a rate limit exception message to me
- This rate limit exception message is parsed incorrectly, triggering JSONDecodeError

I believe this is parsed incorrectly because the OpenAI Python library parses each line in the streamed output separately and assumes each line is JSON. However, the rate limit exception message is pretty-printed JSON and includes internal newlines, so [this call](https://github.com/openai/openai-python/blob/284c1799070c723c6a553337134148a7ab088dd8/openai/api_requestor.py#L765) to `JSON.loads` fails.

This is the line in the streamed output that triggered the error: `"{\"rate_limit_usage\": {\`

Error below:
```
HTTP code 200 from API ("{\"rate_limit_usage\": {\)
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    data = json.loads(rbody)
  File "/Users/xxx/.pyenv/versions/3.10.11/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/xxx/.pyenv/versions/3.10.11/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xxx/.pyenv/versions/3.10.11/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
  File ".venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 232, in <genexpr>
    return (
  File ".venv/lib/python3.10/site-packages/openai/api_requestor.py", line 396, in wrap_resp
    async for r in resp:
  File ".venv/lib/python3.10/site-packages/openai/api_requestor.py", line 725, in <genexpr>
    self._interpret_response_line(
  File ".venv/lib/python3.10/site-packages/openai/api_requestor.py", line 767, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 200 from API ("{\"rate_limit_usage\": {\)
```

### To Reproduce

Call `openai.ChatCompletion.acreate(..., stream=True)` with a prompt that doesn't exceed the rate limit, but whose generated output + prompt exceeds the rate limit.

### OS

macOS

### Python version

Python v3.10.11

### Library version

openai-python v0.28.1

**Comment by mmiguel6288** [comment] 2023-10-12 02:49
I posted a similar bug right before you. I don't think the rate limit needs to be violated to get this error. Even with a very small number of total tokens I am seeing it.

**Comment by jwayne** [comment] 2023-10-12 02:53
Neat. I assumed it was a rate limit error since I was hovering near it, but I didn't validate that (so perhaps i should've have assumed).

Linking your bug: https://github.com/openai/openai-python/issues/649

**Comment by codeslaw** [comment] 2023-10-12 05:57
I am seeing the same issue, and it is happening on calls that previously had no issues completing.  It just started this evening.  Seems like it could be a change to API behavior that the client library can't handle?

**Comment by athyuttamre** [comment] 2023-10-12 07:18
Hi all, we're aware of this issue and have reverted a change that might be causing this. Apologies for the errors here as we continue to investigate the root cause.

**Comment by marioluan** [comment] 2023-10-20 17:26
Maybe related to https://github.com/openai/openai-python/issues/663

**Comment by rattrayalex** [comment] 2023-11-10 03:36
This should be fixed in v1 of this library, please give it a try and let us know if you run into any issues.

**Closed by rattrayalex** 2023-11-10 03:36 UTC
Labels: bug
