### ISSUE TITLE
Use of proxies kwarg in httpx==0.28.0

### ISSUE THREAD

**Issue by DJRHails** [openai/openai-python#1902] opened 2024-11-28 15:37 UTC
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

httpx version 0.28.0 removes the deprecated proxies argument; this argument is hardcoded in the library at the moment.

### To Reproduce

1. Update to httpx version 0.28.0

### Code snippets

```
  File "/var/lang/lib/python3.10/site-packages/openai/_client.py", line 337, in __init__
    super().__init__(
  File "/var/lang/lib/python3.10/site-packages/openai/_base_client.py", line 1438, in __init__
    self._client = http_client or AsyncHttpxClientWrapper(
  File "/var/lang/lib/python3.10/site-packages/openai/_base_client.py", line 1335, in __init__
    super().__init__(**kwargs)
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'
```

### OS

macOS

### Python version

Python 3.10.12

### Library version

openai-1.55.2

**Comment by stestagg** [comment] 2024-11-28 15:44
This is causing a fresh install of openai to be broken currently.

Here's a reproducer:
```
from alpine:edge

RUN apk update
RUN apk add python3 py3-pip

RUN pip install  --break-system-packages openai
RUN python -c 'import openai; client=openai.AsyncOpenAI(api_key="X")'
```

**Comment by Pablo-Merino** [comment] 2024-11-28 15:46
Having this issue too, with the synchronous client. A temporary fix I've found is to hardcode the `httpx` version in my requirements to the previous release, which is `0.27.2`.

Just adding `httpx==0.27.2` makes my code work again.

**Comment by dgellow** [comment] 2024-11-28 15:57
Hi, thank you for the reports, we (@stainless-api) are actively working on a fix.

**Comment by RobertCraigie** [comment] 2024-11-28 16:06
Thanks for the reports, this will be fixed shortly

**Comment by dgellow** [comment] 2024-11-28 16:18
Should be fixed once https://github.com/openai/openai-python/pull/1905 gets merged (all the credits to the amazing @RobertCraigie for the quick fix)

**Comment by RobertCraigie** [comment] 2024-11-28 16:42
Sorry for the delay, we're trying to get a hold of someone with the credentials to publish a new release.

**Closed** 2024-11-28 17:02 UTC
Labels: bug

**Comment by vvaezian** [comment] 2024-12-01 19:43
@dgellow @RobertCraigie In the [pyproject.toml](https://github.com/openai/openai-python/blob/6974a981aec1814b5abba429a8ea21be9ac58538/pyproject.toml#L11) file, the httpx version is defined as `httpx>=0.23.0, <1`. Isn't this too wide? It seems to me the dependent libraries versions should only include the current and tested versions. But `<1` allows many future upgrades that can potentially break stuff like the current issue. Other dependent libraries are defined in the same manner and seems to have the same issue.

**Comment by dgellow** [comment] 2024-12-02 14:11
Hi @vvaezian, thanks for pointing that out. I tend to agree. That's something we identified and will be discussing today as part of our internal post-mortem for that httpx v0.28.0 incident. I expect we will share an update later today in this thread

**Comment by kristapratico** [comment] 2024-12-02 20:02
@dgellow @RobertCraigie FYI it looks like we need the same fix in the CLI: https://github.com/openai/openai-python/blob/534d6c58f6c07d219ca74dd336eaca59d48d0ada/src/openai/cli/_cli.py#L179-L182

**Comment by RobertCraigie** [comment] 2024-12-02 20:05
ah good catch thank you!

**Comment by dgellow** [comment] 2024-12-05 14:29
@vvaezian Following up on your question, we decided against narrowing the version constraints. Instead we decided to invest into improving our testing setup to be sure we have coverage for nightly/dev versions of httpx (and other core dependencies), before they are released publicly.
