### ISSUE TITLE
OpenAI fine-tune shows "That model doesn't exist"

### ISSUE THREAD

**Issue by dwaipayan05** [openai/openai-python#69] opened 2022-01-29 19:33 UTC
I have already trained a fine-tuned model. I am able to retrieve the details of the model using Open AI API. However, when I am using it in a Completion.create() it gives "This model doesn't exist".

Any reason as to why this happened ?

I have already been charged for the fine-tune training process. It also shows up on my account.

**Comment by schnerd** [comment] 2022-01-29 20:47
Hi there! We've responded to the support request you sent in on our site, so I'll close this issue and we can discuss there (the issue is unrelated to the openai python package itself)

**Closed by schnerd** 2022-01-29 20:47 UTC

**Comment by codegod1992** [comment] 2023-02-03 21:02
Hi, There, I met the same error. my mpdel was fine tuned, but "that model doesn't exist err" is occured.
How can I fix this bug?

**Comment by SrikanthanNK** [comment] 2023-05-08 06:12
OpenAI fine-tune shows "That model doesn't exist"
I trained / fine tuned the model, but getting error like 
The model `ABCD` does not exist
What could be the issue ?

**Comment by SrikanthanNK** [comment] 2023-05-09 06:35
HI Schnerd,

I could able to resolve above issue, 
Thanks a lot for your support.

**Comment by minhdirox** [comment] 2023-11-21 10:34
> HI Schnerd,
> 
> I could able to resolve above issue, Thanks a lot for your support.

@SrikanthanNK How did you resolve your issue?

**Comment by nagarajutv11** [comment] 2023-11-23 05:58
I resolved this issue.

Just created a new API Key and it works for me.
