### ISSUE TITLE
The official example for Function Calling doesn't work with SDK version 1.1.1

### ISSUE THREAD

**Issue by mikulskibartosz** [openai/openai-python#703] opened 2023-11-07 06:35 UTC
## Expected behavior

The "Example with one function called in parallel" code from the documentation should correctly show how to use the function call feature. 

## Actual behavior

I get `BadRequestError: Error code: 400 - {'error': {'message': "'content' is a required property - 'messages.1'", 'type': 'invalid_request_error', 'param': None, 'code': None}}` while running the code.

Stack trace:

```
BadRequestError                           Traceback (most recent call last)
[<ipython-input-73-3a60881757d5>](https://localhost:8080/#) in <cell line: 77>()
     75         )  # get a new response from the model where it can see the function response
     76         return second_response
---> 77 print(run_conversation())

5 frames
[<ipython-input-73-3a60881757d5>](https://localhost:8080/#) in run_conversation()
     70                 }
     71             )  # extend conversation with function response
---> 72         second_response = openai.chat.completions.create(
     73             model="gpt-3.5-turbo-1106",
     74             messages=messages,

[/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    297                         msg = f"Missing required argument: {quote(missing[0])}"
    298                 raise TypeError(msg)
--> 299             return func(*args, **kwargs)
    300 
    301         return wrapper  # type: ignore

[/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py](https://localhost:8080/#) in create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, max_tokens, n, presence_penalty, response_format, seed, stop, stream, temperature, tool_choice, tools, top_p, user, extra_headers, extra_query, extra_body, timeout)
    554         timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    555     ) -> ChatCompletion | Stream[ChatCompletionChunk]:
--> 556         return self._post(
    557             "/chat/completions",
    558             body=maybe_transform(

[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in post(self, path, cast_to, body, options, files, stream, stream_cls)
   1053             method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1054         )
-> 1055         return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
   1056 
   1057     def patch(

[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in request(self, cast_to, options, remaining_retries, stream, stream_cls)
    832         stream_cls: type[_StreamT] | None = None,
    833     ) -> ResponseT | _StreamT:
--> 834         return self._request(
    835             cast_to=cast_to,
    836             options=options,

[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
    875             # to completion before attempting to access the response text.
    876             err.response.read()
--> 877             raise self._make_status_error_from_response(err.response) from None
    878         except httpx.TimeoutException as err:
    879             if retries > 0:
```

## Versions

OpenAI SDK: 1.1.1
Python: 3.10.12

**Comment by RobertCraigie** [comment] 2023-11-07 09:36
Have you verified that you've received access to the new API yet? I ran this example earlier and it worked as expected for me.

**Comment by mikulskibartosz** [comment] 2023-11-07 10:42
@RobertCraigie, I think it's unrelated to having access to the new API or the model because it fails during the second call, line: `second_response = openai.chat.completions.create(`. The first one worked fine, and I received the function name with its arguments.

**Comment by mikulskibartosz** [comment] 2023-11-07 10:47
@unconv `del response_message.function_call` removes the function with its arguments from the conversation, so it won't be available to the AI model while it generates subsequent messages. It may affect the results because the model can access the function's response (that you provide) but doesn't know the query anymore (it's removed from the chat).

**Comment by unconv** [comment] 2023-11-07 11:58
@mikulskibartosz It won't affect the results since it is deleted only if it is `None` (see the if statement it's wrapped in). The problem is the library is sending `content` and `function_call` as `None` but the API doesn't allow that. Setting `content` to an empty string in case it is `None` and removing `function_call` altogether when it is `None` solves the issue.

**Comment by bgonzalezfractal** [comment] 2023-11-08 00:13
@unconv patch is working, although I do needed to remove the function call as it was None as well, tried replacing it what "" but did not work, in order to make the example work:
```
response_message = response.choices[0].message
tool_calls = response_message.tool_calls
response_message = dict(response.choices[0].message)
if response_message["content"] is None:
    response_message["content"] = ""
if response_message["function_call"] is None:
    del response_message["function_call"]
```

**Comment by cjpark-data** [comment] 2023-11-08 11:49
@bgonzalezfractal
Thank you. I solve this problem with your solution.

**Comment by RobertCraigie** [comment] 2023-11-09 17:12
Is this report for the example defined here? https://platform.openai.com/docs/guides/function-calling/parallel-function-calling

Or is it somewhere else? That example runs successfully without modification for me.

**Comment by mikulskibartosz** [comment] 2023-11-09 19:22
Yes. It was this example

**Comment by enochcheung** [comment] 2023-11-09 23:07
@mikulskibartosz @unconv @cjpark-data @miwiley 

Hi!

We're looking into this issue, but have not been able to reproduce this on our end. From your reports, we suspect that this is due to the first API request missing `content` in its response message, which would be a bug. This causes the second API request to fail since you are just adding the message from the API response of the first request. However, we have not been able to observe this behavior in our API either. Given that we are using the exact same snippet, this is very odd.

Is this something that occurs consistently on your end? If possible, we'd love to see the full output of the FIRST request as well. We appreciate your help in helping us figure this out!

**Comment by unconv** [comment] 2023-11-10 00:43
@enochcheung @mikulskibartosz @cjpark-data @miwiley

I wasn't able to reproduce the problem when running in a virtual environment, so I checked the difference between `pip freeze` in the in the virtual environment and without it.

Turns out `pydantic==1.10.12` was the issue.

**Running `pip install --upgrade pydantic` solves the problem.**

**Comment by enochcheung** [comment] 2023-11-10 00:48
Interesting! Thank you for digging into this, this is super useful for us. We'll look into ways to try to be more resilient here.

**Comment by miwiley** [comment] 2023-11-10 09:51
The only changes in the code is:

FAIL = 
```
    tool_calls = response_message.tool_calls
    print ("Tools being called", response_message.tool_calls)
    response_message = response.choices[0].message <---------
    
```

SUCCESS =

```
    response_message = dict(response.choices[0].message)    <--- convert to dict
    if response_message["function_call"]    <---check
        del response_message["function_call"]    <--del
```


#FAILURE [LOGS]
```
ask_gpt called latest news in maui <--my route/module call
User Input: latest news in maui <--incoming
Initial Messages: [{'role': 'user', 'content': 'latest news in maui'}]

[FIRST RESPONSE]
Initial API response ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_UW87QII3EMQZMSwY26pQvK8L', function=Function(arguments='{"input":"latest news in Maui"}', name='get_online_data'), type='function')])
Total tokens used 103

[FUNCTION CALL]
Tools being called [ChatCompletionMessageToolCall(id='call_UW87QII3EMQZMSwY26pQvK8L', function=Function(arguments='{"input":"latest news in Maui"}', name='get_online_data'), type='function')]

[ERROR]
Error code: 400 - {'error': {'message': "'content' is a required property - 'messages.1'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

#SUCCESS [LOGS]
```
ask_gpt called latest news in maui   <--my route/module call
User Input: latest news in maui  <--incoming
Initial Messages: [{'role': 'user', 'content': 'latest news in maui'}]

[FIRST RESPONSE]
Initial API response ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_PspTCyFADZx5Iiw3Qvr2Nxwo', function=Function(arguments='{"input":"latest news in Maui"}', name='get_online_data'), type='function')])
Total tokens used 103

[FUNCTION CALL]
Tools being called [ChatCompletionMessageToolCall(id='call_PspTCyFADZx5Iiw3Qvr2Nxwo', function=Function(arguments='{"input":"latest news in Maui"}', name='get_online_data'), type='function')]

[SECOND RESPONSE]
second_response ChatCompletion(id='chatcmpl-8JI6I5zb7GHBjnQzjYPWb7j7MjKcI', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content="The latest news in Maui includes updates on the recovery efforts following the devastating wildfires, the announcement of a $150 million fund to help wildfire victims' families and survivors, and ongoing efforts to support affected residents. There are also reports on the impact of the wildfires on the community and the progress in the search for missing individuals. Additionally, there are updates on various relief efforts and initiatives aimed at supporting those affected by the wildfires.", role='assistant', function_call=None, tool_calls=None))], created=1699608502, model='gpt-3.5-turbo-1106', object='chat.completion', system_fingerprint='fp_eeff13170a', usage=CompletionUsage(completion_tokens=84, prompt_tokens=2884, total_tokens=2968))

Python 3.9.6

Pydantic version in failure
Name: pydantic
Version: 1.10.12

pip3 install --upgrade pydantic
--- Successfully installed pydantic-2.4.2 pydantic-core-2.10.1

#[WORKING AFTER PYDANTIC UPGRADE]
--removed dict,del

[LOGS]
ask_gpt called latest news in maui
User Input: latest news in maui
Initial Messages: [{'role': 'user', 'content': 'latest news in maui'}]

[FIRST RESPONSE]

Initial API response ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_oC6CEoCRsAzaqroMgD8cLIQl', function=Function(arguments='{"input":"latest news in Maui"}', name='get_online_data'), type='function')])
Total tokens used 103

[FUNCTION CALL]

Tools being called [ChatCompletionMessageToolCall(id='call_oC6CEoCRsAzaqroMgD8cLIQl', function=Function(arguments='{"input":"latest news in Maui"}', name='get_online_data'), type='function')]

[SECOND RESPONSE]

second_response ChatCompletion(id='chatcmpl-8JIPORfrJXSmH3oHfTmFTasCF6AP4', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content='Some of the latest news in Maui include updates on the recovery efforts following the wildfires, the creation of a fund to help wildfire victims and survivors, contracts awarded for temporary elementary schools, and ongoing updates about the impact and aftermath of the wildfires. For more detailed information, you can visit websites such as Maui Now, KHON2, and the Maui News.', role='assistant', function_call=None, tool_calls=None))], created=1699609686, model='gpt-3.5-turbo-1106', object='chat.completion', system_fingerprint='fp_eeff13170a', usage=CompletionUsage(completion_tokens=71, prompt_tokens=2908, total_tokens=2979))

**Comment by RobertCraigie** [comment] 2023-11-10 11:06
Thanks for the details and figuring out the cause was Pydantic v1! I've identified the difference in behaviour internally and should have a fix out later today.

**Comment by RobertCraigie** [comment] 2023-11-10 16:10
This will be fixed in the next release! https://github.com/openai/openai-python/pull/776/files

**Comment by roger-zr-wang** [comment] 2023-11-10 19:47
> @enochcheung @mikulskibartosz @cjpark-data @miwiley
> 
> I wasn't able to reproduce the problem when running in a virtual environment, so I checked the difference between `pip freeze` in the in the virtual environment and without it.
> 
> Turns out `pydantic==1.10.12` was the issue.
> 
> **Running `pip install --upgrade pydantic` solves the problem.**

This is exactly the solution for me!

**Comment by rattrayalex** [comment] 2023-11-11 02:24
Fixed in https://github.com/openai/openai-python/releases/tag/v1.2.3

(upgrading pydantic also works)

**Closed by rattrayalex** 2023-11-11 02:24 UTC

**Comment by miwiley** [comment] 2023-11-11 09:10
> Fixed in https://github.com/openai/openai-python/releases/tag/v1.2.3
> 
> (upgrading pydantic also works)

Outstanding! Cheers.

**Comment by raw-gulp-karma** [comment] 2025-10-17 22:05
> Thanks for the details and figuring out the cause was Pydantic v1! I've identified the difference in behaviour internally and should have a fix out later today.





https://outcrop-daire57.github.io/pgmxYsIgx9rviKJa36KXUBUPpGC5cSw_9hL7Vxn0cj-1W8IdXJZvtvRmUHryAUc_jQ/
