### ISSUE TITLE
Chat Completion Hangs after error 500

### ISSUE THREAD

**Issue by keenhon** [openai/openai-python#560] opened 2023-08-03 23:38 UTC
### Describe the bug

Hi,

Chat Completion hang at the next call after a 500 error. My code printed the error below. After that at the next Chat Completion call, it just stuck there.

The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 90c93658c303560e33e5d459254eae54 in your email.) {
  "error": {
    "message": "The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 90c93658c303560e33e5d459254eae54 in your email.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

### To Reproduce

1. Call chatcompletion
2. Get a 500 error from openai
3. Call chatcompletion again
4. hang

### OS

Windows

### Python version

Python 3.10.11

### Library version

openai-0.27.2

**Comment by logankilpatrick** [comment] 2023-09-06 11:58
Hey @keenhon please let me know if this is still an issue for you! Closing this for now.

**Closed by logankilpatrick** 2023-09-06 11:58 UTC
Labels: bug

**Comment by jmy48** [comment] 2024-04-02 00:31
Why is this completed? getting the same problem

**Comment by rattrayalex** [comment] 2024-04-02 00:38
500 errors should not be reported on the SDK repos - they are caused by problems in the backend API.
