### ISSUE TITLE
Using 'logit_bias' to prevent chatgpt or gpt4 from stop generating

### ISSUE THREAD

**Issue by ArvinZhuang** [openai/openai-python#363] opened 2023-04-02 04:03 UTC
### Describe the bug

I have reported [here](https://github.com/openai/openai-cookbook/issues/312), but probably I should also report here.

Hi, 
as the example in the official documentation, we can pass `logit_bias={"50256": -100}` to the `Completion` API to prevent the <|endoftext|> token from being generated.

I'm trying to do the same for `ChatCompletion` but it seems doesn't work.

### To Reproduce

Here is an example:
```
import os
import openai
openai.api_key = os.getenv("OPENAI_API_KEY")

completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": "Hello!"}
    ],
    logit_bias={'100257': -100}
)
```
where I get `<|endoftext|>` token id for `gpt-3.5-turbo` by:
```
import tiktoken
print(tiktoken.encoding_for_model('gpt-3.5-turbo').eot_token)

#results: 100257
```

I still getting `"finish_reason": "stop"` in the returned response.

I also found a positive value works. If set logit_bias={'100257': 100}, the generation will stop immediately and return an empty string message. Seems only negative value doesn't work. Is this a bug or on purpose?

### OS

macOS

### Python version

Python3.8

### Library version

v0.27.2

**Comment by hym3242** [comment] 2023-04-26 21:59
I think maybe tokens that can terminate a generation is not just `<|endoftext|>`. Maybe 100265:`<|im_end|>` is used more, however tokens beyond 100257 are out of our control using logit_bias. If this is the case this would not be a bug but a feature request: requesting more control via logit_bias.

**Comment by hym3242** [comment] 2023-05-11 00:13
Further information on this: if you examine the vocabularies in the 50k tokenizers, they have only one special token `<|endoftext|>` as stop token, however `cl100k_base` tokenizer has tokens like `<|im_end|>`, `<|im_sep|>`, which may be the root cause of this problem. We really need more control of special tokens beyond `<|endoftext|>`!

**Comment by rattrayalex** [comment] 2024-03-03 00:48
Thanks for the suggestion!

This sounds like a feature request for the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue.

Would you mind reposting at [community.openai.com](https://community.openai.com)?

**Closed by rattrayalex** 2024-03-03 00:48 UTC
Labels: bug
