### ISSUE TITLE
Feature Request: return dollar amount for OpenAI request response

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [openai/openai-python#513] opened 2023-06-30 08:00 UTC
### Describe the feature or improvement you're requesting

Add the dollar amount to the response, or a separate function to calculate the same.

### Additional context

The openai library returns the number of tokens with each response.
However, the pricing keeps changing. Is there a way you can add the dollar amount to that response, or a separate function for the same?

Thanks

**Comment by endolith** [comment] 2023-07-10 10:47
Duplicate of https://github.com/openai/openai-python/issues/448

**Comment by Alisultani1** [comment] 2023-07-10 11:03
Ok

**Comment by rattrayalex** [comment] 2023-11-10 04:39
Thanks for the request; I don't expect this to happen anytime soon, but I've passed it along. It certainly would be quite nice to have.

I'm going to close this issue because it's not a bug in the Python library.

**Closed by rattrayalex** 2023-11-10 04:39 UTC
