### ISSUE TITLE
Suppressing token 100265 `<|im_end|>` using logit_bias results in InvalidRequestError

### ISSUE THREAD

**Issue by microsoftbuild** [openai/openai-python#572] opened 2023-08-13 05:22 UTC
### Describe the bug

When trying to ban the sampling of token 100265 using `logit_bias` by mapping it to -100, I get:
```
{'error': {'message': "Invalid key in 'logit_bias': 100265. Maximum value is 100257.", 'type': 'invalid_request_error', 'param': 'logit_bias', 'code': None}}
```
As you are aware 100257 is `<|endoftext|>` and it can be suppressed currently to get full length (of `max_tokens`) completions on the Completions API.

However its equivalent on chat completions API i.e `100265` → `<|im_end|>` can’t be used on chat completions API.

I am curious is intentional (safety reasons) to limit tokens till 100257 OR it is inherited by reusing the old completion API spec.

### To Reproduce

Simply pass a bias: `{100265: -100}` to the `logit_bias` param of chat completion request.

This results in:
```console
Exception has occurred: InvalidRequestError
Invalid key in 'logit_bias': 100265. Maximum value is 100257.
  File "dir/tokenext.py", line 12, in <module>
    reply = openai.ChatCompletion.create(model="gpt-3.5-turbo",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openai.error.InvalidRequestError: Invalid key in 'logit_bias': 100265. Maximum value is 100257.
```
### Code snippets

```Python
import openai
openai.api_key = "API_KEY"  # supply your API key however you choose

conversation = [{
    "role": "user",
    "content": input("Input:")
}]

bias = {100265: -100}

print("GPT: ")
reply = openai.ChatCompletion.create(model="gpt-3.5-turbo",
                                     messages=conversation,
                                     max_tokens=1000,
                                     logit_bias=bias)
print(reply)
```

### OS

macOS

### Python version

Python v3.11.2 64-bit

### Library version

openai-python v0.27.7

**Comment by boyd-openai** [comment] 2023-08-15 22:48
Could you clarify your use case for suppressing 100257 / 100265?

**Comment by microsoftbuild** [comment] 2023-08-16 09:31
Hi @boyd-openai I'm try to generate detailed completions using models available on chat completion. Suppressing the sampling of 100265 will help in doing that consistently regardless of the prompt.

100257 can already be suppressed with `logit_bias` for models on the completion endpoint.

Conversely, enabling `logit_bias` for 100265 can also allow it to be sampled more often for shorter responses. This can help increase reliability for applications using models for semantic logic.

**Comment by asoans** [comment] 2023-09-27 06:08
GPT 3.5 has a max token limit and tokens beyond it can't be directly controlled using 'logit_bias'

**Comment by rattrayalex** [comment] 2023-11-10 03:45
This is not a bug in the Python library, so I'm closing the issue. If you'd still like to see it addressed, please open a thread at community.openai.com.

**Closed by rattrayalex** 2023-11-10 03:45 UTC
Labels: bug
